### ISSUE TITLE
Polish Design

### ISSUE THREAD

**Issue by keivanshahida** [cuappdev/icefishing#118]
# **TO DO**
- [x] Implement Style Guide (Global Font and Colors)
- [x] New Pull to Refresh Design
- [ ] Update/clear out image assets
- [ ] Test on all compatible devices
- [x] Update Splash Screen
- [x] Fix Settings Profile Pic
- [ ] TIFFANY UPDATE ZEPLIN. then check that designs are consistent with Zeplin.io

**Comment by keivanshahida** [comment]
Add splash screen

**Comment by keivanshahida** [comment]
Fix profile picture dimensional ratio

**Comment by aelshaer** [comment]
Make pause button vertical bars slightly thicker

Edit from Tiffany: Updated design on Zeplin. New icon on Tempo Icon dropbox.

**Comment by tz226** [comment]
Sticky Cell Fixes: 
- Change the pause/play icons for the Sticky Cell player. 
- Change font to match (see Zeplin)

Most up to date tempo icons here: https://www.dropbox.com/sh/dgmgucufdcg3amo/AAAJDD5wi6P-CZmZdX_2CO-Ka?dl=0

**Comment by keivanshahida** [comment]
Onboard animation

**Comment by tz226** [comment]
Expanded Player: Keep all of the action buttons on the bottom at all times.  
- if you aren't logged into spotify and click on the 'save to spotify' button, you should be prompted to log in. 
- even if you aren't logged in and you click on open to spotify, you should be directed to the song on spotify.

**Comment by keivanshahida** [comment]
Settings Profile Pic

**Comment by tz226** [comment]
Logo is squished on the Loading Screen (at least on a iPhone 5s). 
@self Might need to modify text styles to be more consistent across the app.

**Comment by keivanshahida** [comment]
Test on all compatible devices BEFORE shipping

**Comment by keivanshahida** [comment]
Update pull to refresh to match new logo

**Comment by tz226** [comment]
Match text style to the UI Kit I will hopefully get out soon lollol cries...

**Comment by tz226** [comment]
UI Kit up ([dropbox link ](https://cornellappdev.slack.com/files/tiffanyzheng/F37A4FG80/tempo_uikit_11.28.16.sketch )and on zeplin) 

*[Colors](https://zpl.io/Zhrkmi) needs updating across the app. Worth mentioning is that there is a difference between read cell color and background color but BG color is only seen on settings page and when refreshing. Otherwise read cell color is used. 
* ALL FONT SHOULD BE AVENIR NEXT. (Line spacing is 22px). I tried to stick to [5 different font sizes](https://zpl.io/ZXdHy3) and only a handful of colors. Note, I know that the font might look small for now. But to ship it, let's stick to the decided sizes because or else spacing gets weird and lots of things need to be redone. Sorry y'all we'll revisit the sizes and perhaps scale across the app. 
* spacing. not much more needs to be said except ik it's a pain but super nice if this gets done. 

Idk lemme know what I can do to help. When the next test flight comes out, I can help by compare screenshots vs UI Kit designs and point out what need to be fixed if that is a good method?

**Comment by acheng96** [comment]
I can take up this issue :)

**Comment by say25** [comment]
Global font and colors file (style guide) might make some sense 😃

**Comment by keivanshahida** [comment]
# **TO DO**
- [ ] Implement Style Guide (Global Font and Colors)
- [ ] New Pull to Refresh Design
- [ ] Update/clear out image assets
- [ ] Test on all compatible devices
- [ ] Update Splash Screen
- [ ] Fix Settings Profile Pic

**Comment by anniexcheng** [comment]
- [x] Loading Screen
- [x] Login Screen
- [x] Username Creation Screen
- [x] Connect to Spotify Screen
- [x] About Screen
- [x] Settings Screen
- [x] Liked Screen
- [x] Users Screen
- [x] Profile Screen
- [x] Feed Screen
- [x] Post a Track Screen
- [x] Follow Suggestions Screen
- [x] No Posts Screen
- [x] Saved/Removed Song Popup View
- [x] Post History Screen
- [x] Collapsed Player View
- [x] Expanded Player View
- [x] Side Bar View Controller
