### ISSUE TITLE
Tempo takes too much space

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/icefishing#263]
![image_uploaded_from_ios_720](https://cloud.githubusercontent.com/assets/7183643/23028836/82daf97c-f436-11e6-9456-1bbbb074485f.jpg)

Need to clear whatever cache we're using to store downloaded songs

**Comment by ChenJesse** [comment]
I think the Haneke cache for images is the problem, I just got mine from 17MB to 325MB just by scrolling through too many images by searching for songs. The weird thing is that clearing the cache (which is done on logout/login of user) doesn't seem to be lowering the storage for some reason...I'll keep looking into it

jk now I think the culprit is the AVAudioPlayer...it looked like it was Haneke since they both occur when you search songs
