### ISSUE TITLE
Add Spotify '+' Button to Liked View

### ISSUE THREAD

**Issue by say25** [cuappdev/icefishing#97]
Button should behave in same way. Should simply have to add button and use functionality from PlayerTableViewController.swift

**Comment by lucasderraugh** [comment]
Although I closed this, @ChenJesse I'd still like you to work on a way for the + to be flushed with the left side. I'd rather have the functionality in though for now.

**Comment by say25** [comment]
Also @ChenJesse LikedCells' album artwork should not rotate. I believe this stems from PlayerTableVC.swift but should be investigated.
Solutions:
1. Stop rotation
2. Make Images Round

**Comment by ChenJesse** [comment]
So that means that the post history cells shouldn't rotate either? And is there a mockup of where the + button should also be? Not exactly sure how I would implement the change in positioning elegantly either...maybe I could just programmatically shift the button location to wherever we actually want it?
